server:
  port: ${SERVER_PORT:8080}

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:5432}/staff-management
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${DB_USER:staff-management-user}
    password: ${DB_PASSWORD:staff-management-pass}
  jpa:
    hibernate.ddl-auto: create
    show-sql: ${JPA_SHOW_SQL:true}
