server:
  port: ${SERVER_PORT:8080}

spring:
  sql.init.mode: always
  datasource:
    url: jdbc:mysql://${DB_HOST:173.20.0.5}:${DB_PORT:3306}/${DB_NAME:staff-management-service}
    driverClassName: com.mysql.jdbc.Driver
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:pass}
  jpa:
    hibernate.ddl-auto: create
    show-sql: ${JPA_SHOW_SQL:true}
    defer-datasource-initialization: true