### Get hours per users - Returns forbidden without admin creds
GET http://localhost:8080/api/hours?order=DESC
Authorization: {{user-basic-auth}}

### Get hours per users
GET http://localhost:8080/api/hours?order=DESC
Authorization: {{admin-basic-auth}}

### Get hours per users ordered and with date filter
GET http://localhost:8080/api/hours?order=DESC&from=2022-12-01&to=2022-12-15
Authorization: {{admin-basic-auth}}